yaml

---
title: "letsHerp: An Interface to the Reptile Database"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{letsHerp}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

This package was developed to facilitate the processes of reptile nomenclature update based on a search for species synonyms according to [The Reptile Database](https://reptile-database.reptarium.cz) website (Uetz et al., 2025).

Currently, the package accesses many species information from the Reptile Database using R interface.

I hope it to be useful to people trying to match databases from different sources (IUCN, species traits database, etc), or trying to get summaries from a given higher taxa or region (e.g.: Snakes from Brazil). But it can also just print single species information directly in R.

Any feedback, suggestion or request are welcome!

### **Download**

The package is available on CRAN, check if the installed version is 1.0.0 or above. If not, the development version can be installed from GitHub.

To install the stable version of this package, users must run:

```{.r}
# Install CRAN version (check package version, must be 1.0.0 or above)
install.packages("letsHerp")

#OR

# Install development version from GitHub
# install.packages("devtools")
devtools::install_github("joao-svalencar/letsHerp")

library(letsHerp)
```

### **List of functions and examples**

**NOTE:** Some functions use parallel processing by default. Parallel processing may affect system performance. Adjust the number of cores according to your needs.


#### **Function `herpSearch`:**

Retrieves species information from The Reptile Database using a binomial name.
```{.r}
# single species:
herpSearch(binomial = "Apostolepis adhara")

# If user wants to check the list of references related to species, as listed in RDB:
herpSearch(binomial = "Bothrops pauloensis", getRef=TRUE)
```

`herpSearch()` supports synonym-based queries. If the provided binomial does not match any currently valid species name, the function automatically passes the query to `herpAdvancedSearch(synonym = binomial)`. In such cases, if the synonym can be unambiguously resolved to a valid species, the function will return the corresponding species information. Otherwise, it provides a link (which can be accessed using `herpSpecies(url = link)`) to a list of all species that include the queried synonym in their synonymy.


#### **Function `herpAdvancedSearch`:**

Creates a link for a page as derived from an Advanced Search in RD (multiple species in a page):
```{.r}
# create multiple species link:
link_boa <- herpAdvancedSearch(genus = "Boa") #returns a link to a list of all Boa species

link_apo <- herpAdvancedSearch(genus = "Apostolepis") #returns a link to a list of all Apostolepis species

link <- herpAdvancedSearch(higher = "snakes", location = "Brazil") #returns a link to a list of all snake species in Brazil

link <- herpAdvancedSearch(year = "2010 OR 2011 OR 2012") #returns a link to a list of all species described from 2010 to 2012
```

`herpAdvancedSearch(synonym = "example")` will return the species information directly (via `herpSearch("example")`) if the synonym uniquely matches a single valid species.


#### **Function `herpSpecies`:**

Retrieve species data from the species link created by `herpAdvancedSearch`. User can also copy and paste the url from a RD webpage containing the list of species derived from an advanced search. It includes higher taxa information, authors, year of description, and the species url. By default this function uses parallel processing, with default set to use half of the available cores. If user wants to use just one core, there are options for backup saving based on the `checkpoint` argument.

```{.r}
#check number of available cores:
install.packages("parallel")
parallel::detectCores()

# sample multiple species data:
#Returns higher taxa information and species url:
boa <- herpSpecies(link_boa, taxonomicInfo = TRUE, getLink = TRUE) #link from herpAdvancedSearch(genus = "Boa")

#example 2
apo <- herpSpecies(link_apo, taxonomicInfo = TRUE, getLink = TRUE) #link from herpAdvancedSearch(genus = "Apostolepis")

#Returns only species url - Faster and recommended for large datasets:
boa <- herpSpecies(link_boa, taxonomicInfo = FALSE, getLink = TRUE) #link from herpAdvancedSearch(genus = "Boa")

#example 2
apo <- herpSpecies(link_apo, taxonomicInfo = FALSE, getLink = TRUE) #link from herpAdvancedSearch(genus = "Apostolepis")

#With checkpoint and backups (only without parallel sampling: a lot slower but safer):
path <- "path/to/save/backup_file.rds" #not to run just example 
apo <- herpSpecies(link_apo, taxonomicInfo = FALSE, getLink = TRUE, checkpoint=6, backup_file=path) #link from herpAdvancedSearch(genus = "Apostolepis")
```

⚠️ **Note:**

All console messages, warnings, and progress updates can be silenced. However, `herpSpecies()` issues a helpful warning if any species information fails to be retrieved, along with instructions on how to access those entries from the function output.


#### **Function `herpSynonyms`:**

Samples species synonyms either using binomial or a data frame with species names and the species link (e.g.: the result of `herpSpecies(link, getLink=TRUE)`). By default this function uses parallel processing, with default set to use half of the available cores.

```{.r}
#check number of available cores:
install.packages("parallel")
parallel::detectCores()

# sample species synonyms
boa_syn <- herpSynonyms(boa) # using data frame created, with herpSpecies(boa_link, getLink = TRUE)
Bconstrictor_syn <- herpSynonyms(x = "Boa constrictor") # using species binomial

#example 2
apo_syn <- herpSynonyms(apo)
```

⚠️ **Note:**

All console messages, warnings, and progress updates can be silenced. However, `herpSynonyms()` issues a helpful warning if any species information fails to be retrieved, along with instructions on how to access those entries from the original data frame.

The complex `regex` pattern used to sample synonyms from The Reptile Database is quite efficient, but still samples about 0.2% in an incorrect format. Most cases represent unusual nomenclature so users might not face any problems trying to match current valid names. In any case, I fixed (potentially) all unusual synonym formats in the internal dataset `allSynonyms` (last update: 23rd May, 2025)


#### **Function `herpSync`:**

Initially inspired in function aswSync from package [AmphiNom](https://github.com/hcliedtke/AmphiNom) (Liedtke, 2018).

This is the most recursive function of the package, using all the previous functions in order to provide the most likely updated nomenclature for the queried species. By default this function uses parallel processing, with default set to use half of the available cores.

The function is divided in two main steps. Here is how it works:

**Step 1**

The function queries a vector of species (e.g.: IUCN, or a regional list), check their validity through `herpSearch` and returns a data frame with current valid species names. When `herpSearch` finds a species page it assumes that is the valid name for the queried species and returns the status "up_to_date". When `herpSearch` doesn't find a species it parses the binomial to `herpAdvancedSearch` using the synonym filter. If `herpAvancedSearch` returns a link for a species page that species name is considered valid for the synonym queried and the function returns the status `"updated"`. Otherwise, `herpAvancedSearch` will return a link for a page with a list of species, then the function assumes that the queried synonym could be assigned to any of those valid names and returns the status: `"ambiguous"`. If the queried species does not return a species page nor a page for multiple species the function returns to column "RDB" the sentence `"not_found"` and to column `"status"` the word `"unknown"`.

**Step 2**

Step 2 is activated only if `solveAmbiguity = TRUE`. When `herpAvancedSearch` returns a link for a page with a list of species, that link is parsed to `herpSpecies` which collects species names and `urls` and automatically parses the resulting data frame to `herpSynonyms`. Finally, with the result of `herpSynonyms` the function compares the queried species with all listed synonyms. If the queried species is actually listed as a synonym of only one of the searched species (e.g. the queried name is not a synonym, but is mentioned in the comments section), the function will return that valid name and status will be `"updated"`. If the queried species is actually a synonym of more than one valid species, then the function will return both species names and the status will still be `"ambiguous"`.

```{.r}
#check number of available cores:
install.packages("parallel")
parallel::detectCores()

# comparing synonyms:
query <- c("Vieira-Alencar authoristicus",
           "Boa atlantica",
           "Boa diviniloqua",
           "Boa imperator",
           "Boa constrictor longicauda")

herpSync(query)

#example 2:
query <- c("Vieira-Alencar authorisensis",
           "Apostolepis ambiniger",
           "Apostolepis cerradoensis",
           "Elapomorphus assimilis",
           "Apostolepis tertulianobeui",
           "Apostolepis goiasensis")

herpSync(query)
```

The column `"RDB"` shows current valid name according to The Reptile Database.

Pay special attention to the `"status"` column:

**status:**

- `"up_to_date"` - Species name provided is the current valid name found in The Reptile Database
 
- `"updated"` - Species name provided is a synonym, and the current valid name is reported unambiguously.

- `"ambiguous"` - Species name provided is considered a synonym of more than one current valid species, likely from a split in taxonomy.

- `"unknown"` - Species name provided in query is not a current valid name nor synonym according to The Reptile Database. This status could be derived from a typo within species name. A very rare situation where this status can pop up is when the current valid name is updated in the query but is not found in the list of synonyms.

- `"duplicated"` - Multiple names in the query are now considered synonyms of a single valid species, likely from a synonymization.

⚠️ **ATTENTION!**⚠️ 

`letsHerp` does not make authoritative taxonomic decisions. It matches input names against currently accepted names in The Reptile Database (RDB). 

A name marked as `"up_to_date"` may still refer to a taxon that has been split, and thus may not reflect the most recent population-level taxonomy, see function `herpSplitCheck` below.


#### **Function `herpSplitCheck`:**

Species names in recent databases are most likely marked with the status `"up_to_date"`. However, the function `herpSync` only indicates whether the queried binomial is currently valid. In some cases, a species may have undergone a taxonomic split, where part of its original populations retains the name while others have been described as new species. `herpSync` does not account for such cases, so it is recommended to review all `"up_to_date"` species for potential taxonomic splits.

To assist with this, the function `herpSplitCheck` queries binomial names as synonyms using `herpAdvancedSearch`, and checks whether any associated species were described after a user-defined date (e.g., the publication date of the dataset being used). By default this function uses parallel processing, with default set to use half of the available cores.

```{.r}
query <- c("Tantilla melanocephala",
           "Atractus snethlageae",
           "Oxybelis aeneus")

herpSplitCheck(query, pubDate = 2019) # pubDate of Nogueira et al., Atlas of Brazilian Snakes
```

The column `"RDB"` shows the current valid names according to The Reptile Database.

Pay special attention to the `"status"` column:

**status:**

- `"up_to_date"` – The species name provided is not a synonym of any species described after `pubDate`.

- `"check_split"` – The species name provided is a synonym of at least one valid species described in or after `pubDate`, suggesting a possible taxonomic split.

**OBS: ** If the queried species is a synonym of only species described in the same year `pubDate` that are already included in the queried species list, the queried species will receive the status `"up_to_date"`.

#### **Function `herpTidySyn`:**

This function was developed exclusively to improve the visualization of `herpSync` and `herpSplitCheck` outcomes. Queried species with many current valid names would break the data frame visualization in the R console. `herpTidySyn` stacks current valid names and improves data visualization. Moreover, the argument `filter`, allows users to filter the printed data frame by "status" so users can focus only in the status that they want to evaluate.

```{.r}
query <- c("Vieira-Alencar authorisensis",
           "Apostolepis ambiniger",
           "Apostolepis cerradoensis",
           "Elapomorphus assimilis",
           "Apostolepis tertulianobeui",
           "Apostolepis goiasensis")

df <- herpSync(query)
herpTidySyn(df)
```

### **Internal datasets**

- The package counts with a full list of current valid species (`allReptiles` - 12,440 species) with their respective higher taxa information (updated to May 23rd, 2025);

- A dataset with all unique synonyms for each current valid species (`allSynonyms` - 53,159 entries - updated to May 23rd, 2025); 

- Another synonyms dataset with all entries considering their respective references (`allSynonymsRef` - 110,413 entries - updated to May 23rd, 2025).

### **How to Cite**

To get the full reference to cite this package in publications, run to get the most up to date version reference:

```{.r}
citation("letsHerp")
```

⚠️ **Important note**

`letsHerp` retrieves valuable taxonomic and synonymy data directly from [The Reptile Database](http://www.reptile-database.org).

When citing this package, please also cite the original database as a data source.

### **References**
Liedtke, H. C. (2018). AmphiNom: an amphibian systematic tool. Systematics and Biodiversity, 17(1) 1-6. https://doi.org/10.1080/14772000.2018.1518935

Nogueira, C. C., Argôlo, A. J. S., Arzamendia, V., Azevedo, J. A. R., Barbo, F. E., Bérnils, R. S., … & Martins, M. (2019). Atlas of Brazilian Snakes: Verified Point-Locality Maps to Mitigate the Wallacean Shortfall in a Megadiverse Snake Fauna. South American Journal of Herpetology, 14(sp1), 1–274. http://dx.doi.org/10.2994/sajh-d-19-00120.1 

Uetz, P., Freed, P, Aguilar, R., Reyes, F., Kudera, J. & Hošek, J. (eds.) (2025). [The Reptile Database](http://www.reptile-database.org)

### **Author:**
João Paulo dos Santos Vieira de Alencar

Email: joaopaulo.valencar@gmail.com

[Orcid](https://orcid.org/0000-0001-6894-6773) | [ResearchGate](https://www.researchgate.net/profile/Joao-Paulo-Alencar)
